version: '3'
services:
  greengrass:
    image: public.ecr.aws/amazonlinux/amazonlinux:2023
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - greengrass_data:/data
      - /var/run/greengrass:/var/run/greengrass
    ports:
      - "1441:1441"
      - "1442:1442"
    environment:
      - FORCE_REDEPLOY=${FORCE_REDEPLOY}
      - VERBOSE=true
    entrypoint: /data/greengrass_entrypoint.sh
    restart: unless-stopped
    
volumes:
  greengrass_data:
